import '@/styles/index.scss'
import Head from 'next/head'
import DesktopNavbar from '../components/desktopNavbar';
import MobileNavbar from '../components/mobileNavbar';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

config.autoAddCss = false;

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Maria Paz Abarca</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='main'>
        <DesktopNavbar />
        <MobileNavbar />
        <div className='content'>
          <Component {...pageProps} />
          <footer>
            <a href="https://www.flaticon.com/free-icons/moon" title="moon icons" rel="noreferrer" target="_blank">
              Moon icons created by Freepik - Flaticon
            </a>
          </footer>
        </div>
      </div>
    </>
  )
}
