import '@/styles/index.scss'
import Head from 'next/head'
import DesktopNavbar from '../components/molecules/desktopNavbar';
import MobileNavbar from '../components/molecules/mobileNavbar';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Maria Paz Abarca</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopNavbar />
      <MobileNavbar />
      <Component {...pageProps} />
    </>
  )
}
